# Generated by Django 4.2.6 on 2023-11-01 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaLogs',
            fields=[
                ('reminder', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.IntegerField(blank=True, default=0, null=True)),
                ('completedAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
