# Generated by Django 4.2.6 on 2023-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_yogalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogalogs',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
