# Generated by Django 4.2.6 on 2023-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_yogalogs_deliveredat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogalogs',
            name='deliveredAt',
        ),
        migrations.AlterField(
            model_name='yogalogs',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
